CREATE TABLE COLABORADOR(
    	MATRICULA VARCHAR(10) NOT NULL,
	CPF VARCHAR(20) NOT NULL,
	NOME VARCHAR(50) NOT NULL,
	SALARIO DECIMAL(10,2) NOT NULL,
	DEPARTAMENTO VARCHAR(10) NOT NULL,
	ENDERECO_ID VARCHAR(10) NOT NULL,
	DEPENDENTE_ID VARCHAR(10),
	TELEFONE_ID VARCHAR(10) NOT NULL,
	EMAIL_ID VARCHAR(10) NOT NULL,
 PRIMARY KEY (MATRICULA)
);


CREATE TABLE ENDERECO_COLAB(
    ID VARCHAR(10) NOT NULL,
    LOGRADOURO VARCHAR(50) NOT NULL,
    COMPLEMENTO VARCHAR(50),
    BAIRRO VARCHAR(50) NOT NULL,
    CIDADE VARCHAR(50) NOT NULL,
    ESTADO CHAR(2) NOT NULL,
    CEP VARCHAR(10) NOT NULL,
    COLABORADOR  VARCHAR(10) NOT NULL,
PRIMARY KEY(ID)
);


CREATE TABLE TELEFONE_COLAB(
    ID VARCHAR(10) NOT NULL,
    TELEFONE_1 VARCHAR(20) NOT NULL,
    TELEFONE_2 VARCHAR(20),
    COLABORADOR VARCHAR(10) NOT NULL,
PRIMARY KEY(ID)
);


CREATE TABLE EMAIL_COLAB(
    ID VARCHAR(10) NOT NULL,
    EMAIL_PESSOAL VARCHAR(50) NOT NULL,
    EMAIL_CORPORATIVO VARCHAR(50) NOT NULL,
    COLABORADOR VARCHAR(10) NOT NULL,
PRIMARY KEY(ID)
);


CREATE TABLE DEPENDENTE(
    CPF VARCHAR(20) NOT NULL,
    NOME VARCHAR(50) NOT NULL,
    DATA_NASCIMENTO DATE NOT NULL,
    PARENTESCO VARCHAR(20) NOT NULL
    COLABORADOR VARCHAR(10) NOT NULL,
PRIMARY KEY(ID)
);


CREATE TABLE DEPARTAMENTO(
    SIGLA VARCHAR(10) NOT NULL,
    NOME VARCHAR(50) NOT NULL,
    CHEFE VARCHAR(10) NOT NULL,
    DEPARTAMENTO_SUPERIOR VARCHAR(10) NOT NULL,
PRIMARY KEY(SIGLA)
);


CREATE TABLE PROJETO(
    ID VARCHAR(10) NOT NULL,
    NOME VARCHAR(50) NOT NULL,
    INICIO DATE NOT NULL,
    TERMINO DATE NOT NULL
    RESPONSAVEL VARCHAR(10) NOT NULL,
PRIMARY KEY(ID)
);


CREATE TABLE PAPEL(
    ID VARCHAR(10) NOT NULL,
    NOME VARCHAR(50) NOT NULL,
PRIMARY KEY(ID)
);


CREATE TABLE ATRIBUICAO(
    COLABORADOR VARCHAR(10) NOT NULL,
    PROJETO VARCHAR(10) NOT NULL,
    PAPEL VARCHAR(10) NOT NULL,
PRIMARY KEY(COLABORADOR, PROJETO, PAPEL)
);