
-- Inserção de um novo registro na tabela BRH_PROJETO
INSERT INTO BRH.PROJETO (NOME, RESPONSAVEL, INICIO, FIM)
VALUES ('PSQL', 'E123', TO_DATE('2023-10-06', 'YYYY-MM-DD'), TO_DATE('2023-12-31', 'YYYY-MM-DD'));
