alter session set "_ORACLE_SCRIPT"=true;

// Inserção  de novo colaborador

SELECT * FROM BRH.COLABORADOR;

SELECT * FROM BRH.ENDERECO;

INSERT INTO BRH.ENDERECO
    (CEP, UF,CIDADE, BAIRRO)
VALUES
('71124-261', 'SP', 'Osasco', 'Bela Vista');


INSERT INTO BRH.COLABORADOR
(MATRICULA, CPF, NOME, SALARIO, DEPARTAMENTO, CEP, LOGRADOURO, COMPLEMENTO_ENDERECO)
VALUES
('A124', '325.358.328-58', 'Fulano de Tal', 2967, 'SEOPE', '71124-261', 'Rua do Exercicio', 'Casa 4');

SELECT * FROM BRH.DEPENDENTE;

INSERT INTO BRH.DEPENDENTE
(CPF, NOME, DATA_NASCIMENTO, PARENTESCO, COLABORADOR)
VALUES
('556.584.487-54','Beltrana de Tal', '23/07/2022', 'Filho(a)','A124');

INSERT INTO BRH.DEPENDENTE
(CPF, NOME, DATA_NASCIMENTO, PARENTESCO, COLABORADOR)
VALUES
('145.584.457-54','Cicrana de Tal', '13/09/2076', 'CÃ´njuge','A124');


SELECT * FROM BRH.EMAIL_COLABORADOR;

INSERT INTO BRH.EMAIL_COLABORADOR
(EMAIL, COLABORADOR, TIPO)
VALUES
('fulano@email.com','A124', 'P');

INSERT INTO BRH.EMAIL_COLABORADOR
(EMAIL, COLABORADOR, TIPO)
VALUES
('fulano.tal@brh.com','A124', 'T');

SELECT * FROM BRH.TELEFONE_COLABORADOR;

INSERT INTO BRH.TELEFONE_COLABORADOR
(NUMERO, COLABORADOR, TIPO)
VALUES
('(61) 9 9999-9999','A124', 'C');

INSERT INTO BRH.TELEFONE_COLABORADOR
(NUMERO, COLABORADOR, TIPO)
VALUES
('(61) 3030-4040','A124', 'R');


SELECT * FROM BRH.PAPEL;

INSERT INTO BRH.PAPEL
(ID, NOME)
VALUES
(8, 'Especialista de Negócios');

SELECT * FROM BRH.PROJETO;

INSERT INTO BRH.PROJETO
(ID, NOME, RESPONSAVEL, INICIO, FIM)
VALUES
(9, 'BI', 'A124', '23/09/2023','');

SELECT * FROM BRH.ATRIBUICAO;

INSERT INTO BRH.ATRIBUICAO
(COLABORADOR, PROJETO, PAPEL)
VALUES
('A124', 9, 8);