CREATE TABLE TB_COLABORADOR(
MATRICULA_COL VARCHAR2(10),
CPF VARCHAR2 (11),
NOME VARCHAR2 (100),
EMAIL_PESSOAL VARCHAR2(100),
EMAIL_COORPORATIVO VARCHAR2 (100),
LOGRADOURO VARCHAR2(150),
NUMERO INTEGER,
BAIRRO VARCHAR2(50),
CIDADE VARCHAR2(50),
ESTADO VARCHAR2(2),
CEP VARCHAR2(8),
SALARIO NUMBER(6,2),
SIGLA_DO_DEPTO VARCHAR2(10)
);

CREATE TABLE TB_DEPENDENTE(
CPF VARCHAR2 (11),
NOME VARCHAR2 (100),
DATA_NASCIMENTO DATE,
PARENTESCO VARCHAR2(10),
MATRICULA_COL VARCHAR2(10)
);

CREATE TABLE PROJETO(
ID_PROJETO VARCHAR2(20),
NOME VARCHAR2(20),
INICIO DATE,
FIM DATE
);

CREATE TABLE ATRIBUICAO(
ID_PROJETO VARCHAR2(20),
MATRICULA_COL VARCHAR2(10),
PAPEL VARCHAR2(20)
);

CREATE TABLE DEPARTAMENTO(
SIGLA_DO_DEPTO VARCHAR2(10),
NOME_DO_DEPTO VARCHAR2 (20),
CHEFE VARCHAR2 (50),
DEP_SUPERIOR VARCHAR(20)
);

CREATE TABLE DEPARTAMENTO_SUPERIOR(
SIGLA_DO_DEPTO VARCHAR2(10),
DEP_SUPERIOR VARCHAR(20)
);