SELECT
    MATRICULA,
    NOME,
    SALARIO,
    CASE
        WHEN SALARIO <= 3000 THEN 'Júnior'
        WHEN SALARIO <= 6000 THEN 'Pleno'
        WHEN SALARIO <= 20000 THEN 'Sênior'
        ELSE 'Corpo diretor'
    END AS NIVEL_SENIORIDADE
FROM BRH_COLABORADOR
ORDER BY NIVEL_SENIORIDADE, NOME;
