-- CONSULTA_DEPENDETE_COLABORADOR

SELECT
    C.NOME AS "Nome do Colaborador",
    COUNT(D.COLABORADOR) AS "Quantidade de Dependentes"
FROM BRH_COLABORADOR C
LEFT JOIN BRH_DEPENDENTE D ON C.MATRICULA = D.COLABORADOR
GROUP BY C.MATRICULA, C.NOME
HAVING COUNT(D.COLABORADOR) >= 2
ORDER BY "Quantidade de Dependentes" DESC, "Nome do Colaborador" ASC;