SELECT C##BRH.DEPENDENTE.*,C##BRH.COLABORADOR.nome AS "Nome do Colaborador"  
FROM C##BRH.DEPENDENTE 
INNER JOIN C##BRH.COLABORADOR 
ON C##BRH.COLABORADOR.MATRICULA = C##BRH.DEPENDENTE.COLABORADOR
WHERE (EXTRACT(MONTH FROM C##BRH.DEPENDENTE.DATA_NASCIMENTO) IN (4,5,6))
OR (UPPER(C##BRH.DEPENDENTE.NOME) LIKE '%H%') ORDER BY C##BRH.COLABORADOR.nome,C##BRH.DEPENDENTE.NOME;