SELECT * FROM COLABORADOR;
INSERT INTO COLABORADOR 
(MATRICULA, CPF, NOME, SALARIO, DEPARTAMENTO, CEP, LOGRADOURO, COMPLEMENTO_ENDERECO) 
VALUES 
('A124', '124.245.658-20', 'Fulano de Tal', '5000', 'SEDES', '71777-700', 'Rua das rosas', '100');


SELECT * FROM PAPEL;
INSERT INTO PAPEL (ID, NOME) VALUES (8, 'Especialista de Negócios');

SELECT * FROM PROJETO;
INSERT INTO PROJETO 
(ID, NOME, RESPONSAVEL, INICIO) 
VALUES 
('5', 'BI', 'A124', '16/02/24');

SELECT * FROM TELEFONE_COLABORADOR;
INSERT INTO TELEFONE_COLABORADOR 
(NUMERO, COLABORADOR, TIPO) 
VALUES 
('(61) 9 9999-9999', 'A124','C');
INSERT INTO TELEFONE_COLABORADOR 
(NUMERO, COLABORADOR, TIPO) 
VALUES 
('(61) 3030-4040', 'A124','R');

SELECT * FROM EMAIL_COLABORADOR;
INSERT INTO EMAIL_COLABORADOR
(EMAIL, COLABORADOR, TIPO)
VALUES
('fulano@email.com','A124','P');
INSERT INTO EMAIL_COLABORADOR
(EMAIL, COLABORADOR, TIPO)
VALUES
('fulano.tal@brh.com','A124','T');

SELECT * FROM DEPENDENTE;
INSERT INTO DEPENDENTE
(CPF, NOME, DATA_NASCIMENTO, PARENTESCO, COLABORADOR)
VALUES
('987.789.524-01','Cicrana de Tal', '03/03/92', 'Cônjuge','A124');
INSERT INTO DEPENDENTE
(CPF, NOME, DATA_NASCIMENTO, PARENTESCO, COLABORADOR)
VALUES
('321.321.456-75','Joaquim de Tal', '29/06/24' , 'Filho(a)','A124');


SELECT * FROM ENDERECO;

SELECT * FROM DEPARTAMENTO;



-- Relatório de cônjuges
SELECT 
 C.NOME AS NOME_COLABORADOR
,D.NOME AS NOME_DEPENDENTE
,D.DATA_NASCIMENTO AS DATA_NASCIMENTO_DEPENDENTE
FROM
COLABORADOR C INNER JOIN DEPENDENTE D
ON C.MATRICULA = D.COLABORADOR WHERE D.PARENTESCO = 'Cônjuge';


--Filtrar dependentes
SELECT NOME,data_nascimentO, TO_CHAR(data_nascimento, 'MONTH') AS MES_NASCIMENTO FROM dependente WHERE TO_CHAR(data_nascimento, 'MM')  IN('04','05','06') OR (nome LIKE '%h%' OR nome LIKE '%H%') ORDER BY nome ASC;


-- Listar colaborador com maior salário
SELECT nome, salario FROM colaborador WHERE salario = (SELECT MAX(salario) FROM colaborador);


-- Relatório de senioridade
SELECT matricula, NOME, salario, 
(CASE WHEN salario <= 3000 THEN 'Júnior'
    WHEN salario > 3000 AND salario <= 6000 THEN 'Pleno'
    WHEN salario > 6000 AND salario <= 20000 THEN 'Sênior'
    ELSE 'Corpo diretor'
END) SENIORIDADE
FROM COLABORADOR ORDER BY SENIORIDADE, NOME;


--Relatório de contatos
SELECT 
 c.NOME
,tc.numero
,tc.tipo AS TIPO_TEL
,ec.email
,ec.tipo AS TIPO_EMAIL
FROM 
    COLABORADOR C
INNER JOIN
    TELEFONE_COLABORADOR TC
ON c.matricula = tc.colaborador

INNER JOIN
    EMAIL_COLABORADOR EC
ON c.matricula = Ec.colaborador
WHERE (tc.tipo = 'M' OR tc.tipo = 'C') AND ec.tipo = 'T'
ORDER BY c.nome;


COMMIT;