// Inserir novo colaborador

SELECT * FROM BRH.COLABORADOR;

INSERT INTO BRH.COLABORADOR (MATRICULA, CPF, NOME, SALARIO, DEPARTAMENTO, CEP, LOGRADOURO, COMPLEMENTO_ENDERECO)
VALUES
('A666','381.121.298-71','Fulano de Tal','10500', 'DEPTI', '01153-000', 'Rua Vitorino Carmilo', '830');

SELECT * FROM BRH.PAPEL;

INSERT INTO BRH.PAPEL (ID, NOME)
VALUES
('8', 'Especialista de Negócios')

SELECT * FROM BRH.PROJETO;

INSERT INTO BRH.PROJETO (ID, NOME, RESPONSAVEL, INICIO, FIM)
VALUES
('9', 'BI', 'A666', '01/01/2024', '01/06/2024')

SELECT * FROM BRH.ATRIBUICAO;

INSERT INTO BRH.ATRIBUICAO (COLABORADOR, PROJETO, PAPEL)
VALUES
('A666','381.121.298-71','Fulano de Tal','10500', 'DEPTI', '01153-000', 'Rua Vitorino Carmilo', '830');

SELECT * FROM BRH.ENDERECO;

INSERT INTO BRH.ENDERECO (CEP, UF, CIDADE, BAIRRO)
VALUES
('01153-000','SP','São Paulo','Barra Funda');

SELECT * FROM BRH.TELEFONE_COLABORADOR;

INSERT INTO BRH.TELEFONE_COLABORADOR (NUMERO, COLABORADOR, TIPO)
VALUES
('(61) 9 9999-9999','A666','M');

INSERT INTO BRH.TELEFONE_COLABORADOR (NUMERO, COLABORADOR, TIPO)
VALUES
('(61) 3030-4040','A666','R');

SELECT * FROM BRH.EMAIL_COLABORADOR;

INSERT INTO BRH.EMAIL_COLABORADOR (EMAIL, COLABORADOR, TIPO)
VALUES
('fulano@email.com','A666','P');

INSERT INTO BRH.EMAIL_COLABORADOR (EMAIL, COLABORADOR, TIPO)
VALUES
('fulano.tal@brh.com','A666','T');

SELECT * FROM BRH.DEPENDENTE;

INSERT INTO BRH.DEPENDENTE (CPF, NOME, DATA_NASCIMENTO, PARENTESCO, COLABORADOR)
VALUES
('365.365.598-91','Beltrana de Tal','01/01/1987','Filho(a)', 'A666');

INSERT INTO BRH.DEPENDENTE (CPF, NOME, DATA_NASCIMENTO, PARENTESCO, COLABORADOR)
VALUES
('365.315.598-91','Cicrana de Tal','01/01/1955','CÃ´njuge', 'A666');

// Relatório de departamentos

SELECT SIGLA, NOME FROM BRH.DEPARTAMENTO;

// Relatório de dependentes

SELECT NOME FROM BRH.COLABORADOR; 
SELECT NOME FROM BRH.DEPENDENTE;
SELECT DATA_NASCIMENTO FROM BRH.DEPENDENTE;
SELECT PARENTESCO FROM BRH.DEPENDENTE;

SELECT C.nome AS "NOME DO COLABORADOR", D.nome AS "NOME DO DEPENDENTE",
D.data_nascimento AS "DATA DE NASCIMENTO DO DEPENDENTE", D.parentesco  
FROM BRH.COLABORADOR C JOIN BRH.DEPENDENTE D ON  D.COLABORADOR = C.MATRICULA;

// Excluir departamento SECAP 

SELECT * FROM BRH.DEPARTAMENTO;
DELETE FROM BRH.DEPARTAMENTO WHERE SIGLA = 'SECAP';

// Relatório de contatos

SELECT C.nome AS "NOME DO COLABORADOR", E.Email AS "EMAIL COORPORATIVO", T.numero
AS "CELULAR" FROM BRH.COLABORADOR C 
JOIN BRH.EMAIL_COLABORADOR E ON  E.COLABORADOR = C.MATRICULA AND E.TIPO = 'T'
JOIN BRH.TELEFONE_COLABORADOR T ON T.COLABORADOR = C.MATRICULA AND T.TIPO = 'M'
ORDER BY (C.NOME);


