alter session set "_ORACLE_SCRIPT"=true;

CREATE USER brh_normalizacao
	IDENTIFIED BY brh_normalizacao
	DEFAULT TABLESPACE users
	QUOTA UNLIMITED ON users;
    
    create table brh.colaboradornormalizacao (
	matricula varchar2(10) not null,
    salario decimal(10,2) not null,
    departamento varchar2(6) NOT NULL);
    
    ALTER TABLE brh.colaboradornormalizacao ADD CONSTRAINT PK_colaboradornormalizacao 
    PRIMARY KEY (matricula)
    

    
    create table brh.departamentonormalizacao (
	sigla varchar2(6) not null,
    departamento_superior varchar2(30) NOT NULL,
    chefe varchar2(30) NOT NULL);
    ALTER TABLE OS

    ALTER TABLE brh.departamentonormalizacao ADD FOREIGN KEY (departamento_superior) REFERENCES chefe ;
    
    ALTER TABLE brh.departamentonormalizacao ADD CONSTRAINT PK_departamentonormalizacao
    PRIMARY KEY (sigla)
    
    create table brh.cadastro (
	cpf char(14) not null,
	nome varchar2(255) not null,
    cep varchar2(10) not null,
    estado varchar2(2) not null,
    cidade varchar2(255) not null,
	bairro varchar2(255) not null,
    complemento varchar2(255),
    telefone varchar2(255) not null,
    email varchar2(255) not null);
    
    create table brh.dependente1(
	cpf char(14) not null,
	nome varchar2(255) not null,
    data_nascimento date not null,
	parentesco varchar2(20) not null);
    
    ALTER TABLE brh.dependente1 ADD CONSTRAINT PK_dependente1
    PRIMARY KEY (cpf)
    
    create table brh.projeto1 (
    id integer GENERATED BY DEFAULT AS IDENTITY (START WITH 5) NOT NULL,
	responsavel varchar2(10),
	inicio date not null,
	fim date);
    
    create table brh.papel1 (
    id integer GENERATED BY DEFAULT AS IDENTITY (START WITH 5) NOT NULL,
	fim date);
    
    create table brh.projeto1 (
    id integer GENERATED BY DEFAULT AS IDENTITY (START WITH 5) NOT NULL,
	responsavel varchar2(10),
	inicio date not null,
	fim date);
   