DECLARE
  V_NOME VARCHAR2(200);
  V_RESPONSAVEL VARCHAR2(200);
  V_RETORNO VARCHAR2(200);
BEGIN
  V_NOME := 'ORACLE 19c';
  V_RESPONSAVEL := 'A1234';

  INSERE_PROJETO(
    P_NOME => V_NOME,
    P_RESPONSAVEL => V_RESPONSAVEL,
    P_RETORNO => V_RETORNO
  );
--   Legacy output: 
DBMS_OUTPUT.PUT_LINE('V_RETORNO = ' || V_RETORNO);
--  :P_RETORNO := P_RETORNO;
--rollback; 
END;
